### ISSUE TITLE
Want code?

### ISSUE THREAD

**Issue by alexander255** [lathiat/nss-mdns#12]
Hi I think I've been sent to this project as proposed new upstream for `libnss-mdns` and would like to know whether you are planning to assume that role?

If so, please review my issue in the [systemd bug tracker](https://github.com/systemd/systemd/issues/3582). It includes patches for at least issue #5 (both Avahi and legacy mode):

> - Full support for AF_UNSPEC (previous versions just treated AF_UNSPEC as if it was AF_INET) by retrieving, and returning, both IPv4 and IPv6 results in this case.
> - Obtaining/guessing IPv6 scope IDs from avahi or mdns/legacy
> - Support for the _nss_mdns_gethostbyname4_r interface: This interface probably just wasn't around in 2007, but without it, neither AF_UNSPEC addresses nor IPv6 scope IDs can actually be passed to applications.

If there is interest I can convert this to a GitHub Pull Request.
Let me know what you thing.

**Comment by agoode** [comment]
Hi!

Push requests are probably the best way to get the code looked at. There is a backlog of patches but we definitely want to get through them.

I am pretty sure @lathiat mentioned something about IPv6 scope?

Also, I am trying to remove legacy (see #1).
