### ISSUE TITLE
Merge Gentoo patches

### ISSUE THREAD

**Issue by agoode** [lathiat/nss-mdns#4]
Patches here:
https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-auth/nss-mdns/files

**Comment by agoode** [comment]
Hi @amynka, do you think you could help move the Gentoo patches upstream? I'm not very experienced with Gentoo.

**Comment by Amynka** [comment]
I can try :)

**Comment by agoode** [comment]
Great! Let me know if you need anything. There have been a lot of cleanups lately.

Do the gentoo patches overlap with #13 ?

**Comment by Amynka** [comment]
I would say that it overlaps so it seems the job is done already.

**Comment by agoode** [comment]
Ok, thanks for taking a look. I'll let you know when I get IPv6 merged and then you can rebase or drop your gentoo patches.

**Comment by Amynka** [comment]
Ok thank you :)

**Comment by agoode** [comment]
Can you take a look again? I merged the big chunk of IPv6 code.

**Comment by agoode** [comment]
ping :)

**Comment by Amynka** [comment]
@mgorny  can you check please?

**Comment by mgorny** [comment]
Yes, it's all good already. The other patch was not really necessary, and we've replaced it with `--localstatedir=` configure option. There's also fresh PR #23 straight from Gentoo but it's not included in the patch set yet.

**Comment by agoode** [comment]
I think this is good now. I'm planning on tagging a release soon.
