### ISSUE TITLE
Add a configure option to enable/disable the tests

### ISSUE THREAD

**Issue by tgurr** [lathiat/nss-mdns#44]
Currently there doesn't seem to be a way to disable the tests, this causes a build dependency on check and pkg-config even when not planning to run any tests.

**Comment by agoode** [comment]
There is only a build dependency on pkg-config. check is only used if present.

Are you concerned about the pkg-config dependency?

**Comment by tgurr** [comment]
Not only, actually about the unconditional usage of the pkg-config check for check. Such automagic stuff causes problem for source-based distributions where we need to be able to disable certain stuff even if the packages might be available/installed locally.

**Comment by agoode** [comment]
So it sounds like the solution is to add the proper --with-check/--without-check options, correct?

https://autotools.io/autoconf/arguments.html

**Comment by tgurr** [comment]
Either that or --enable-tests/--disable-tests like quite a few other packages already do to make the tests and it's dependencies (de-)selectable via configure.
