### ISSUE TITLE
Add a configure option to specify the avahi-daemon socket

### ISSUE THREAD

**Issue by tgurr** [lathiat/nss-mdns#45]
Right now the socket location to avahi-daemon is hard-coded in `src/Makefile.am` via
`-DAVAHI_SOCKET=\"$(localstatedir)/run/avahi-daemon/socket\"`
It would be nice to be able to specify this option during configure since the avahi-daemon socket location might as well reside under `/run` directly.

**Comment by agoode** [comment]
Agreed.
