### ISSUE TITLE
cannot resolve hosts in Fedora 29

### ISSUE THREAD

**Issue by gforceg** [lathiat/nss-mdns#66]
I'm running Fedora 29 and unable to resolve "*.local" hosts using nss-mdns.

Avahi seems to be working because when I run `avahi-browse --all --resolve` the hosts appear in the output:

```bash
action@slim ~ avahi-browse --all --resolve
...
= wlp2s0 IPv4 myantsle                                      SSH Remote Terminal  local
   hostname = [myantsle.local]
   address = [192.168.0.34]
   port = [22]
   txt = []
```
But when I try to ping the host by its name it's unresolvable:

```bash
 action@slim ~ ping myantsle.local
ping: myantsle.local: Name or service not known
```

I can ping the same host by IP without any problems:
```bash
action@slim ~ ping 192.168.0.34
PING 192.168.0.34 (192.168.0.34) 56(84) bytes of data.
64 bytes from 192.168.0.34: icmp_seq=1 ttl=64 time=2.09 ms
64 bytes from 192.168.0.34: icmp_seq=2 ttl=64 time=2.64 ms
64 bytes from 192.168.0.34: icmp_seq=3 ttl=64 time=1.87 ms
^C
--- 192.168.0.34 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 1.877/2.203/2.642/0.322 ms
```

I'm sure this has something to do with authselect but I don't know enough about nss, authselect, or avahi to troubleshoot this intelligently. I tried editing '/etc/nsswitch.conf' and '/etc/authselect/nsswitch.conf' directly and then restarting the avahi daemon. Both files contain the line:

```bash
hosts:      files dns mdns4_minimal [NOTFOUND=return] myhostname
```
I'm not sure what else to try.

**Comment by gforceg** [comment]
I also tried making the changes to /etc/authselect/user-nsswitch.conf, running: `sudo authselect apply-changes` and restarting avahi-daemon.

**Comment by gforceg** [comment]
this is working fine when I am on another network. I think it's my cable modem / wifi-router.

**Comment by mintslice** [comment]
Late response, but I fixed it by changing hosts in /etc/nsswitch.conf to:

hosts:      files mdns4_minimal [NotFOUND=return] dns myhostname

I don't think I even needed to restart anything.
