### ISSUE TITLE
Unable to resolve hosts after update

### ISSUE THREAD

**Issue by panbroggi** [lathiat/nss-mdns#80]
Hello everyone.

I have tried to update nss-mdns on my system (using KaOS). I have manually compiled it with [this PKGBUILD](https://github.com/KaOS-Community-Packages/nss-mdns) by replacing the version with v0.15. After the update and a reboot, however,  `ping`, `ssh` and `getent hosts` failed with `hostname.local`. Do I need to change something in the configuration of my `/etc/nsswitch.conf` file?

**Comment by Mek101** [comment]
For starters, what's your `/etc/nsswitch.conf` content?

**Comment by panbroggi** [comment]
Hi! Thanks for replying. The content is this:

```
# Begin /etc/nsswitch.conf

passwd: files systemd
group: files systemd
shadow: files

publickey: files

hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4 myhostname mymachines resolve [!UNAVAIL=return] 
networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files
#End /etc/nsswitch.conf
```

**Comment by bearsh** [comment]
the same happend for me on gentoo. with 0.15 e.g. ping 'returns' a system error...

**Comment by marcan** [comment]
For me (gentoo), mdns_minimal fails but mdns works. I'm not sure what's going on; I see absolutely nothing in `strace` from mdns_minimal (other than the module being loaded). It seems to just refuse to resolve anything.

**Comment by marcan** [comment]
The 0.15 release tarball was botched. It's missing `src/nss.h`. This causes the function names not to be #defined properly, so the only module that works is `mdns` itself - everything else fails to function. This explains why nothing works for @panbroggi, who is using `mdns4`.

**Comment by marcan** [comment]
Pinging @agoode who made the release.

**Comment by marcan** [comment]
This was broken by 99c2f1c1. That commit moved off the prototypes to `nss.h`, but failed to add it to the Makefile, so it is not included in releases. Presumably it still compiles because it ends up picking `<nss.h>` from the system which keeps the compiler happy, but doesn't do what we want.

**Comment by marcan** [comment]
Filed Gentoo [bug 795579](https://bugs.gentoo.org/795579) to drop the broken 0.15 release.

**Comment by agoode** [comment]
Let me take a look at this.

**Comment by agoode** [comment]
Thank you @marcan for figuring this out. It's fixed with 0.15.1 that I just made.

**Comment by agoode** [comment]
Looks like Gentoo is updated to 0.15.1 already?!

Thanks to everyone's help here.

**Comment by thesamesam** [comment]
I try to give good service! Thanks for the fast work, everyone.

**Comment by panbroggi** [comment]
I confirm the issue is gone. The [PKGBUILD on KaOS Community Packages](https://github.com/KaOS-Community-Packages/nss-mdns) is now up-to-date.
Thank you all!
